### ISSUE TITLE
Is it possible to download to a folder other than the one the .py file is in?

### ISSUE THREAD

**Issue by Kerean** [0x776b7364/toggle.sg-download#39]
Up until now, I have been placing the download_toggle_video.py file inside c:\python27 where python resides.  Any videos that I download automatically go into c:\python27.  I was wondering if there is any setting somewhere (perhaps within the .py file itself) that can change the default download folder to another drive or folder?

**Comment by 0x776b7364** [comment]
You can place the script file somewhere else, and then reference your python.exe file as such:

```
c:\my\path> c:\python27\python.exe download_toggle_video2.py http://video.toggle.sg/blah
```

Otherwise, you can hardcode the destination folder by modifying the following line in `download_file()`:

`ffmpeg_download_cmd = 'ffmpeg -hide_banner -loglevel info -i ' + url + " -c copy -bsf:a aac_adtstoasc \"c:\\my\\path\\" + name + ".mp4\""`

**Comment by 0x776b7364** [comment]
Closed due to inactivity.
