### ISSUE TITLE
domain name has changed.the method has been invalid

### ISSUE THREAD

**Issue by ownerowner** [0x776b7364/toggle.sg-download#62]
please update the code.thanks

**Comment by gromgit** [comment]
Not gonna happen, according to [this](https://github.com/0x776b7364/toggle.sg-download/issues/61#issuecomment-571458648).

**Comment by ChinHuiHing** [comment]
@ownerowner maybe u can refer this link https://github.com/ChinHuiHing/toggle.sg-download I have modify a bit the code

**Comment by prokiller1199** [comment]
@ChinHuiHing can you modified the episodes url as well? much thanks

**Comment by ChinHuiHing** [comment]
> @ChinHuiHing can you modified the episodes url as well? much thanks

The episode url I will try it and post to here if it works. But if anyone know how to modified the code to extract the media name will help a lot. This is because the existing code unable to extract the media name so if u download few episode in 1 command line it will overwriting your previous file due to same filename.
